"""Analysis helpers for notebooks (EDA, Theme 1 crosstabs, later modeling)."""

from .crosstabs import (
    brand_vs_label,
    crosstab_performance,
    mannwhitney_wer_by_brand,
    one_way_with_wer,
)
from .data import (
    BRI_COL,
    CLUSTER_COL,
    VIEWS_COL,
    WER_COL,
    coverage_by_brand,
    coverage_summary,
    explode_list_col,
    load_feature_table,
    project_paths,
)
from .metrics import leakage_checklist, outcome_health, skewed_summary
from .plots import (
    brand_compare_hbar,
    brand_wer_violin,
    coverage_bars,
    crosstab_heatmap,
    landscape_hbar,
    outcome_dist_charts,
    performance_bubble,
    relative_uplift_diverging,
    sample_mix_bars,
    scalable_winners_scatter,
)
from .present import (
    brand_pivot_display,
    coverage_annotation,
    humanize_label,
    one_way_display_table,
)
from .within_brand import (
    auto_findings,
    brand_baseline_wer,
    category_vs_rest_tests,
    relative_display_table,
    relative_performance_by_category,
    tests_display_table,
)
from .modeling import (
    LEAKAGE_COLS,
    holdout_eval,
    prepare_model_frame,
    run_grouped_cv,
    summarize_cv,
    wer_to_bri,
)

__all__ = [
    "BRI_COL",
    "CLUSTER_COL",
    "VIEWS_COL",
    "WER_COL",
    "auto_findings",
    "brand_baseline_wer",
    "brand_compare_hbar",
    "brand_pivot_display",
    "brand_vs_label",
    "brand_wer_violin",
    "category_vs_rest_tests",
    "coverage_annotation",
    "coverage_bars",
    "coverage_by_brand",
    "coverage_summary",
    "crosstab_heatmap",
    "crosstab_performance",
    "explode_list_col",
    "holdout_eval",
    "humanize_label",
    "landscape_hbar",
    "LEAKAGE_COLS",
    "leakage_checklist",
    "load_feature_table",
    "mannwhitney_wer_by_brand",
    "one_way_display_table",
    "one_way_with_wer",
    "outcome_dist_charts",
    "outcome_health",
    "performance_bubble",
    "prepare_model_frame",
    "project_paths",
    "relative_display_table",
    "relative_performance_by_category",
    "relative_uplift_diverging",
    "run_grouped_cv",
    "sample_mix_bars",
    "scalable_winners_scatter",
    "skewed_summary",
    "summarize_cv",
    "tests_display_table",
    "wer_to_bri",
]
